# -*- coding: utf-8 -*-
"""GA and Feature Selection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQ2ZUzSIxWWe8gjuAqNhDjDDchRsJYko
"""


"""# **Latest code here**

"""

pip install geneticalgorithm

import pandas as pd
import numpy as np
import sklearn
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from geneticalgorithm import geneticalgorithm as ga

dataset = pd.read_csv('/content/colon_cancer.csv')
numRows, numCols =  np.shape(dataset)


def getIndx(arrayIndx):
  lenArr = len(arrayIndx)
  arrayOutput=np.zeros(lenArr)
  j=0
  for i in range(lenArr):
    if arrayIndx[i] >= 0.5:
      arrayOutput[j] = i
      j=j+1

  if j==0:
    return ([0])

  arrayReturn=np.zeros(j)
  for i in range(j):
      arrayReturn[i] = arrayOutput[i]

  return arrayReturn


def f(combinational_array):

  print('the new ga array is: ')
  print(combinational_array)
  arrayToTest = getIndx(combinational_array)
  print(arrayToTest)


  X=dataset.iloc[0:numRows, arrayToTest].values
  Y = dataset.iloc[0:numRows, numCols-1].values
  X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)
  svmModel  = svm.SVC()
  svmModel.fit(X_train, Y_train)
  X_Predict = svmModel.predict(X_test)
  predictedValue = accuracy_score(X_Predict, Y_test)
  print ("predictedValue: ")
  print(predictedValue)
  return  -1 * predictedValue


#length = 10
length = int(numCols/4)
print("length is : ", length)

varbound=np.array([[0,1]]*length)
model=ga(function=f,dimension=length,variable_type='int', variable_boundaries=varbound)

model.run()
